package guest:handler;

world guest {
    use tsubu-cloud:handler/types.{request, response};

    import tsubu-cloud:logger/logger;
    import tsubu-cloud:postgres/postgres;

    export handler: func(request: request) -> response;
}
